name: gemarbaca
version: 1.0.0+1
publish_to: none
description: Create digital library with flutter and rest api
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  top_snackbar_flutter: ^3.1.0
  shimmer: ^3.0.0
  animated_bottom_navigation_bar: ^1.3.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/img/logo/
    - assets/img/ilustration/