name: gemarbaca
version: 1.0.0+1
publish_to: none
description: Create digital library with flutter and rest api
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  top_snackbar_flutter: ^3.1.0
  shimmer: ^3.0.0
  curved_navigation_bar: ^1.0.3
  flutter_onboarding_slider: ^1.0.11
  lottie: ^3.0.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  flutter_rating_bar: ^4.0.1
  iconsax_flutter: ^1.0.0
  iconsax: ^0.0.8
  connectivity_plus: ^2.3.8
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2
  skeletonizer: ^1.1.0
  quickalert: ^1.1.0
  syncfusion_flutter_pdfviewer: ^24.2.8
  syncfusion_flutter_datepicker: ^24.2.9
  workmanager: ^0.5.2
  flutter_local_notifications: ^17.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/img/logo/play_store_512.png"
#  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_app_name:
  name: "Gemar Baca"

flutter: 
  uses-material-design: true

  assets:
    - assets/img/logo/
    - assets/img/ilustration/
    - assets/img/onboarding/
    - assets/img/default/
    - assets/img/kategori_icon/
    - assets/splash/
    - assets/gif/
